name: NPM Update Bot 🤖

on:
  push:
    branches: backend
  schedule:
    - cron: '0 0 * * 1'

jobs:
  npmupbot:
    name: NPM Update Bot 🤖
    runs-on: ubuntu-latest
    if: github.repository_owner == 'rahulranjandev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: rahulranjandev/real-time-todo
          ref: backend
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
          cache: 'npm'

      - name: Bot 🤖 "Updating NPM Packages..."
        run: |
          npm install -g --silent npm-check-updates
          ncu -u
          npm update
          git config --global user.name 'NPM Update Bot'
          git config --global user.email 'npmupbot@users.noreply.github.com'
          git add .
          git commit -am "npm: package updates" || true
          git push
